### ISSUE TITLE
Error Report

### ISSUE THREAD

**Issue by cpsc-helper** [syxiaobai/AF-NEU#1]
ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'

**Comment by syxiaobai** [comment]
In what context does this problem occur? Import what installation package or run what program?

**Comment by cpsc-helper** [comment]
> In what context does this problem occur? Import what installation package or run what program?

Hi, this problem should be caused by the version inconsistency for tensorflow and keras.
Please specify the detail version  of the tensorflow and keras version used in your local environment.
Also please rename the script 'python entry_2021.py' to 'entry_2021.py'.

**Comment by syxiaobai** [comment]
My file has been updated. Please test it again.

**Comment by cpsc-helper** [comment]
Index of your saved anser is out of bounds, please check your answer output and saving content when you save the output predictions.

Traceback (most recent call last):
  File "score_2021.py", line 166, in <module>
    score_avg = score(TESTSET_PATH, RESULT_PATH)
  File "score_2021.py", line 152, in score
    ue_score = ue_calculate(endpoints_pred, TrueRef.endpoints_true, TrueRef.onset_score_range, TrueRef.offset_score_range)
  File "score_2021.py", line 115, in ue_calculate
    score += onset_score_range[int(start)]
IndexError: index 93840 is out of bounds for axis 0 with size 93839

**Comment by syxiaobai** [comment]
Thank you for your feedback. I have updated the program. Please test it again.
